// --- JavaScript ---
export { isValue } from "./intern/value.js"
export { isType } from "./intern/type.js"
export { isTypeExpression } from "./intern/language.js"
export { isComposition } from "./intern/value.js"
export { isList } from "./intern/value.js"
export { isDictionary } from "./intern/value.js"
export { isRecord } from "./intern/value.js"
export { isTuple } from "./intern/value.js"
export { typeOf } from "./intern/type.js"
export { equals } from "./intern/value.js"
export { parseTypeExpression } from "./intern/language.js"
export { inflate } from "./intern/space.js"
