// --- JavaScript ---
export { Play } from "./intern/scene.js"
export { Role } from "./intern/role.js"
export { isShowing } from "./intern/stage.js"
export { isEscalation } from "./intern/gig.js"
export { isJob } from "./intern/gig.js"
export { isInert } from "./intern/gig.js"
export { isActor } from "./intern/agent.js"
export { isEmployable } from "./intern/agent.js"
export { when } from "./intern/gig.js"
export { play } from "./intern/agent.js"
export { surprise } from "./intern/gig.js"
export { cast } from "./intern/agent.js"
export { mourn } from "./intern/agent.js"
